### ISSUE TITLE
st doesn’t start under velox (“Connection error”)

### ISSUE THREAD

**Issue by stapelberg** [michaelforney/st#1]
I’m trying to launch st revision 2fda4be2babb8952e35ed8f174f6350901f39088 (latest at the time of writing) when running velox. I tried using the key binding from `velox.conf.sample`, and I tried launching st from a weston-terminal instance.

On stderr, st says:

``` text
# find_driver: Trying DRM driver `intel'
wl_display@1: error 1: invalid arguments for xdg_shell@11.get_xdg_surface
# wld_font_open_pattern: Loading font file: /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf
Connection error
```

Find the output of `strace -f -tt -o /tmp/st -s 2048 ./st` at https://gist.github.com/stapelberg/1c1a983d6231f9199db8

Please let me know if you need any other information about my setup.

**Comment by michaelforney** [comment]
Is your swc also the latest revision?

xdg_shell recently added a request `destroy` as the first opcode. This pushed the requests from

0: use_unstable_version, 1: get_xdg_surface, ...

to

0: destroy, 1: use_unstable_version, 2: get_xdg_surface

So I imagine that st is trying to call `use_unstable_version`, but your swc is interpreting it as an invalid `get_xdg_surface` request. The `use_unstable_version` request is meant to catch incompatibilities in the unstable protocol version in between the client and the server, but this doesn't handle the case when the opcode of this first request has changed.

**Comment by stapelberg** [comment]
Indeed, that seems to be the problem. Reverting to git revision cb8abfd49d35df14aed49664608955c9af170ff5 solves it.

I am wondering if there’s a way to make software that uses swc notice such version incompatibilities and complain loudly about them.

**Comment by michaelforney** [comment]
This is what the `use_unstable_version` request is about. The usual scenario is that the unstable version is bumped, the client asks for an older (or newer one), and then the server responds with an error saying the versions are incompatible.

The problem in this case was that not only was the unstable version bumped, but also the opcode of the `use_unstable_version` request changed. There is nothing the server can do about it because from it's perspective, the client is sending an invalid request, which I think is conveyed pretty clearly from the error message on the client side.

This whole thing is temporary anyway until xdg_shell is finalized.
